name: Create LaTeX PDF

on: workflow_dispatch 

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Compile
              uses: xu-cheng/latex-action@v2
              with:
                working_directory: ./franke-report-query-segmentation/franke-report-query-segmentation-paper/
                root_file: franke-report-query-segmentation.tex

            - name: Generate release tag
              run: echo "release_tag=Build_$(date +"%Y.%m.%d_%Hh%Mmin")" >> "$GITHUB_ENV"

            - name: Check Output
              run: tree

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: franke-report-query-segmentation.pdf
                tag_name: ${{ env.release_tag }}              
              if: ${{ github.ref == 'refs/heads/main' }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
